---
title: "How much did restricting mobility help in controlling the spread of COVID?"
author: 'Satheesh Joseph, Paco Valdez, Yi Zhang'
output: pdf_document
---
## Background

The Covid-19 pandemic has taken more than 2.5 million lives worldwide. In the U.S.
alone, more than half a million people died because of it.COVID-19 is thought to 
spread mainly through close contact from person to person, including among people 
who are physically near each other (within about 6 feet).[1]

As the virus spread, many cities and other areas have implemented a shutdown policy
that significantly restricted the mobility of the population. Specifically, many
companies have opted for a complete work-from-home policy.

As a team of Data Scientists, we're interested in assessing the effectiveness of
restricting mobility in controlling the spread of Covid-19.

## Research Question

Rather than investigating the effect of social distancing on a micro and personal
interaction level, we are interested in its effect on a policy level.Specifically,
the Research Question we're asking is:
```
How much did restricting mobility help in controlling the spread of COVID?
```

## Operationalization

To unpack the high level question, there are a few components to this.

**Firstly**, we'll use the [New York Times](https://github.com/nytimes/covid-19-data)
Covid-19 data for the number of Covid cases per State. And we will use the
[COVID-19 Community Mobility Report](https://www.google.com/covid19/mobility/)
for mobility score, specifically the workplace mobility score.

**Secondly**, mobility have drastically different effect on the spread
of the virus depending on the population density. Thus, having the variable 
mobility alone as the causal factor is misleading. Therefore, the population
density per sq. mile is a mandatory variable for all the models. This data will 
come from the [COVID-19 US State Policy Database](www.tinyurl.com/statepolicies).

**And Finally**, we noticed that the Covid cases metric is a time-series data.
Given that Covid symptoms typically start between 2 to 14 days after exposure[1],
we would build in a time delay between the time of the mobility score and
the Covid cases..

We would break the time from March 2020 to March 2021 into 52 weeks, and
stagger the mobility score and the number of cases by 1 week. Therefore the
simplest linear model would be:
$$
total\_cases\_in\_week_{i+1} = \beta_0 + \beta_1 average\_mobility\_in\_week_i + \beta_2 population\_density
$$

For example, each data point would be:
```
x1 = average mobility score of a state between 2020-03-01 and 2020-03-06
x2 = population density of the same state
y = total number of cases between 2020-03-07 and 2020-03-13 of the same state
```

For more advanced models, we will use a few more variables as control, for example
the "Stay at Home" order, or the face mask policy, etc.

## Feasibility Study

A feasibility study of the research question using the given data set is conducted
by the team. Community Mobility Report provides us with the needed insights into 
the relative decrease in mobility across categories of places. Combining the 
insights with the US State Policy data gives us a clear picture of the restrictions 
in place across the USA. Plotting this information on top of the surge in cases data 
from NY times bolstered our confidence to successfully conduct this research. 

Evidence of the exploration is provided below. 

```{r, echo = FALSE, results='hide', message=FALSE, fig.show="hold", out.width="50%"}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
library(sandwich)
library(lmtest)
library(fec16)
library("readxl")
library(ggplot2)
library(babynames) # provide the dataset: a dataframe called babynames
library(dplyr)
library(hrbrthemes)
library(viridis)
# Load the package
library(lubridate)
mr <- read.csv("../data/raw/2020_US_Region_Mobility_Report.csv")
case_data <- read.csv("../data/supplement/all-states-history.csv")

data1 <- case_data %>% 
  filter(state %in% c("CA", "AL", "DC"))
# Keep only 3 names
data1$dt <- as.Date(data1$date)

# Plot

data <- mr %>% 
  filter(sub_region_1 %in% c("California", "Alabama", "District of Columbia")) %>%
  filter(sub_region_2 %in% c("")) %>%
  rename(State = sub_region_1)

# Plot
data %>%
  ggplot( aes(x=date, y=(transit_stations_percent_change_from_baseline), group=State, color=State)) +
    geom_line() +
    scale_color_viridis(discrete = TRUE) +
    ggtitle("Transit station mobility across states") +
    ylab("Deviation from Baseline") +
    xlab("Date")

data1 %>%
  ggplot(aes(x=dt, y=hospitalizedCurrently, group=state, color=state)) +
    geom_line() +
    scale_x_date(date_minor_breaks = "2 weeks") +
    ggtitle("Hospitalizations in CA") +
    ylab("COVID patients") +
    xlab("Date")

```

## References:
```
[1]: https://www.cdc.gov/coronavirus/2019-ncov/faq.html
```











